name: zDiscord
description: A simple /discord command for your Minecraft server
version: 1.5.0-SNAPSHOT
api-version: '1.17'
main: dev.zaviar.zdiscord.zDiscord
authors: [ zaviar.dev ]
folia-supported: true
load: POSTWORLD
commands:
  discord:
    description: Get the discord link to our server
    aliases: [ zdiscord ]