# zDiscord - By zaviar.dev for Minecraft Java 1.21.1

message:
  # Should the message be presented to players upon joining the server?
  presentOnJoin: false
  
  # Set what text lines should players see when they use /discord
  text:
  - "&b&lJoin our discord!"
  - "&fhttps://discord.gg/default"
 
  # Choose what players will see when they hover over the message
  # and what link they should be prompted with when they click it. Nullify to disable.
  textHover: "&fClick to go to our discord"
  textClick: "https://discord.gg/default"

# Mix up your discord command by adding a sound effect,
# Make sure to use the correct sound enum for your Minecraft version!
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound:
  enabled: false
  value: "ENTITY_EXPERIENCE_ORB_PICKUP"